### ISSUE TITLE
How to pass complete style into __init__ constructor? 

### ISSUE THREAD

**Issue by philipsd6** [j0ack/pybeeryaml#4]
I trying to understand how to pass in a dict for the style, instead of just the name, but I can't figure it out. If I pass in `style={"name": "American Wheat or Rye Beer", "category": "Light Hybrid Beer", ...etc...}` I get: `KeyError: 'style'` from this line:

https://github.com/j0ack/pybeeryaml/blob/277f42784db57da3af6e9b006599e96232068ae5/pybeeryaml/recipe.py#L61

As far as I can tell, these two lines make it impossible to pass in a complex style, because if style is a dict, then it tries to load in style from `**data["style"]` (Pythonic style, that should probably be `**kwargs`!) parameters, but it won't be there because it was passed in as a named parameter.

Instead I believe it should be this:

```python
if isinstance(self.style, dict):
    self.style = Style(**style)
```

**Comment by j0ack** [comment]
Hello,

Thanks for the issue. You're absolutely right there is no way to implement a dict style in the current state.
I'll open a PR concerning this issue soon unless you want to submit some code.

**Comment by philipsd6** [comment]
I started to work on a PR, but after looking through the code more, I decided this project is not for me. All I needed was to parse a BSMX recipe/equipment file to convert it to readable YAML. For that I was happy to use [Box](https://github.com/cdgriffith/Box). (Still struggling to determine all of the various enumerations used in BSMX, but nothing helps that when it's not documented anywhere.)

I would love to see this become more of a full-featured schema, and then this code could just define a schema with Cerebus/jsonschema/schema and then load yaml and validate it.

That spec is the difficult part, but once done it could be implemented in XML/YAML whatever. A custom library like this could also implement user-friendly YAML tag features like accepting unit input that gets converted into a unit structure for interchange. Off the top of my head... thinking of something like this:

```yaml
fermentables:
  - name: Pale 2-row Malt:
    type: Grain
    amount: !Pounds 5.0
    yield: !Percent 73.4
    color: !EBC 3.0
```
This would parsed to:
```yaml
fermentables:
  - name: Pale 2-row Malt:
    type: Grain
    amount: {value: 5.0, unit: pounds}
    yield: {value: 73.4, unit: percentage}
    color: {value: 3.0, unit: ebc}
```
